<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Article;

/**
 * @property mixed $id int(10,0) NOT NULL
 * @property mixed $user_id int(10,0) NOT NULL
 * @property mixed $content text(65535) NOT NULL
 * @property mixed $created timestamp NOT NULL
 */
trait ArticleFields
{
}
