<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Article;

use Atlas\Table\Table;

/**
 * @method ArticleRow|null fetchRow($primaryVal)
 * @method ArticleRow[] fetchRows(array $primaryVals)
 * @method ArticleTableSelect select(array $whereEquals = [])
 * @method ArticleRow newRow(array $cols = [])
 * @method ArticleRow newSelectedRow(array $cols)
 */
class ArticleTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'articles';

    const COLUMNS = [
        'id' => [
            'name' => 'id',
            'type' => 'int',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'user_id' => [
            'name' => 'user_id',
            'type' => 'int',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'content' => [
            'name' => 'content',
            'type' => 'text',
            'size' => 65535,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'created' => [
            'name' => 'created',
            'type' => 'timestamp',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'id',
        'user_id',
        'content',
        'created',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'user_id' => null,
        'content' => null,
        'created' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
