<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Customer;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) NOT NULL
 * @property mixed $corp varchar(50) NOT NULL
 * @property mixed $staff varchar(20) NOT NULL
 * @property mixed $mail varchar(100)
 * @property mixed $tel varchar(20)
 * @property mixed $address varchar(255)
 */
class CustomerRow extends Row
{
    protected $cols = [
        'id' => null,
        'corp' => null,
        'staff' => null,
        'mail' => null,
        'tel' => null,
        'address' => null,
    ];
}
