<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Customer;

use Atlas\Table\Table;

/**
 * @method CustomerRow|null fetchRow($primaryVal)
 * @method CustomerRow[] fetchRows(array $primaryVals)
 * @method CustomerTableSelect select(array $whereEquals = [])
 * @method CustomerRow newRow(array $cols = [])
 * @method CustomerRow newSelectedRow(array $cols)
 */
class CustomerTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'customer';

    const COLUMNS = [
        'id' => [
            'name' => 'id',
            'type' => 'int',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'corp' => [
            'name' => 'corp',
            'type' => 'varchar',
            'size' => 50,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'staff' => [
            'name' => 'staff',
            'type' => 'varchar',
            'size' => 20,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'mail' => [
            'name' => 'mail',
            'type' => 'varchar',
            'size' => 100,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'tel' => [
            'name' => 'tel',
            'type' => 'varchar',
            'size' => 20,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'address' => [
            'name' => 'address',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'id',
        'corp',
        'staff',
        'mail',
        'tel',
        'address',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'corp' => null,
        'staff' => null,
        'mail' => null,
        'tel' => null,
        'address' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
