{% extends '/boards/layout.phtml' %}

{% block title %} Board {% endblock %}
{% block header %} Articles {% endblock %}

{% block content %}
<div class="h6 text-right mt-2 mr-4">
    logined: <a href="/board/user/{{ user_id }}">{{ username }}</a>
</div>
<h2 class="h5 mt-4 mb-4">Article content & comment.</h2>
<div class="card">
    <div class="card-body">
        {{ content | raw }}
    </div>
</div>

<table class="table mt-4 mb-0">
    <thead>
    <tr><th>Comment</th><th>username</th></tr>
    </thead>
    <tbody>
    {% for row in comments %}
    <tr>
        <td>{{ row.message }}</td>
        <td>{{ row.users.username }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<div class="card mt-4 mb-4">
    <div class="card-header">
        Comment Form:
    </div>
    <div>
        <form action="/board/article/{{id}}" method="post">
            <div class="form-group">
                <label>Comment</label>
                <input class="form-control" type="text" name="message">
            </div>
            <div><input class="form-control btn-primary" type="submit"></div>
        </form>
    </div>
</div>
<div class="h6 mb-4"><a href="/board">&lt;&lt; go to Top</a></div>
{% endblock %}