<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">
    </head>
    <body class="container">
        <h1 class="display-4">{% block header %}{% endblock %}</h1>
        {% block content %}{% endblock %}
    </body>
</html>