<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\User;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) NOT NULL
 * @property mixed $username varchar(20) NOT NULL
 * @property mixed $password varchar(20) NOT NULL
 * @property mixed $mail varchar(50)
 */
class UserRow extends Row
{
    protected $cols = [
        'id' => null,
        'username' => null,
        'password' => null,
        'mail' => null,
    ];
}
