<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Comment;

/**
 * @property mixed $id int(10,0) NOT NULL
 * @property mixed $user_id int(10,0) NOT NULL
 * @property mixed $article_id int(10,0) NOT NULL
 * @property mixed $message varchar(255) NOT NULL
 */
trait CommentFields
{
}
