{% extends 'layout.phtml' %}

{% block header %}Slim{% endblock %}

{% block content %}
<div>a microframework for PHP</div>
<table class="table">
    <thead>
    <tr><th>ID</th><th>Corp</th>
        <th>Staff</th><th>Mail</th></tr>
    </thead>
    <tbody>
    {% for row in data %}
    <tr>
        <td>{{ row.id }} </td>
        <td>{{ row.corp }} </td>
        <td>{{ row.staff }} </td>
        <td>{{ row.mail }} </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}


