<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8"/>
    <title>{% block title %}{% endblock %}</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300'
          rel='stylesheet' type='text/css'>
    <style>
        body {
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            color: #aaa;
            font-size: 18px;
        }
        h1 {
            color: #719e40;
            font-family: 'Lato', sans-serif;
        }
    </style>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">
</head>
<body class="container">
<h1>{% block header %}{% endblock %}</h1>
{% block content %}{% endblock %}
</body>
</html>
