<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Message;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) NOT NULL
 * @property mixed $user_id int(10,0) NOT NULL
 * @property mixed $message varchar(255) NOT NULL
 * @property mixed $posted timestamp NOT NULL
 */
class MessageRow extends Row
{
    protected $cols = [
        'id' => null,
        'user_id' => null,
        'message' => null,
        'posted' => null,
    ];
}
