<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Product;

/**
 * @property mixed $id int(10,0) NOT NULL
 * @property mixed $name varchar(50) NOT NULL
 * @property mixed $price int(10,0)
 */
trait ProductFields
{
}
