<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Product;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) NOT NULL
 * @property mixed $name varchar(50) NOT NULL
 * @property mixed $price int(10,0)
 */
class ProductRow extends Row
{
    protected $cols = [
        'id' => null,
        'name' => null,
        'price' => null,
    ];
}
