<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Product;

use Atlas\Table\Table;

/**
 * @method ProductRow|null fetchRow($primaryVal)
 * @method ProductRow[] fetchRows(array $primaryVals)
 * @method ProductTableSelect select(array $whereEquals = [])
 * @method ProductRow newRow(array $cols = [])
 * @method ProductRow newSelectedRow(array $cols)
 */
class ProductTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'products';

    const COLUMNS = [
        'id' => [
            'name' => 'id',
            'type' => 'int',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'name' => [
            'name' => 'name',
            'type' => 'varchar',
            'size' => 50,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'price' => [
            'name' => 'price',
            'type' => 'int',
            'size' => 10,
            'scale' => 0,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'id',
        'name',
        'price',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'name' => null,
        'price' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
